mod bindings {
    // These are not auto-generated by bindgen
    #![allow(clippy::missing_safety_doc)]

    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;

mod avutil;
pub use crate::avutil::*;
