use crate::ffi::*;
use crate::util::media;
use crate::utils;
#[cfg(feature = "serialize")]
use serde::{Deserialize, Serialize};

#[allow(non_camel_case_types)]
#[derive(Eq, PartialEq, Clone, Copy, Debug)]
#[cfg_attr(feature = "serialize", derive(Serialize, Deserialize))]
pub enum Id {
    None,

    // video codecs
    MPEG1VIDEO,
    MPEG2VIDEO,
    #[cfg(all(feature = "ff_api_xvmc", not(feature = "ffmpeg_5_0")))]
    MPEG2VIDEO_XVMC,
    H261,
    H263,
    RV10,
    RV20,
    MJPEG,
    MJPEGB,
    LJPEG,
    SP5X,
    JPEGLS,
    MPEG4,
    RAWVIDEO,
    MSMPEG4V1,
    MSMPEG4V2,
    MSMPEG4V3,
    WMV1,
    WMV2,
    H263P,
    H263I,
    FLV1,
    SVQ1,
    SVQ3,
    DVVIDEO,
    HUFFYUV,
    CYUV,
    H264,
    INDEO3,
    VP3,
    THEORA,
    ASV1,
    ASV2,
    FFV1,
    XM4,
    VCR1,
    CLJR,
    MDEC,
    ROQ,
    INTERPLAY_VIDEO,
    XAN_WC3,
    XAN_WC4,
    RPZA,
    CINEPAK,
    WS_VQA,
    MSRLE,
    MSVIDEO1,
    IDCIN,
    BPS8,
    SMC,
    FLIC,
    TRUEMOTION1,
    VMDVIDEO,
    MSZH,
    ZLIB,
    QTRLE,
    TSCC,
    ULTI,
    QDRAW,
    VIXL,
    QPEG,
    PNG,
    PPM,
    PBM,
    PGM,
    PGMYUV,
    PAM,
    FFVHUFF,
    RV30,
    RV40,
    VC1,
    WMV3,
    LOCO,
    WNV1,
    AASC,
    INDEO2,
    FRAPS,
    TRUEMOTION2,
    BMP,
    CSCD,
    MMVIDEO,
    ZMBV,
    AVS,
    SMACKVIDEO,
    NUV,
    KMVC,
    FLASHSV,
    CAVS,
    JPEG2000,
    VMNC,
    VP5,
    VP6,
    VP6F,
    TARGA,
    DSICINVIDEO,
    TIERTEXSEQVIDEO,
    TIFF,
    GIF,
    DXA,
    DNXHD,
    THP,
    SGI,
    C93,
    BETHSOFTVID,
    PTX,
    TXD,
    VP6A,
    AMV,
    VB,
    PCX,
    SUNRAST,
    INDEO4,
    INDEO5,
    MIMIC,
    RL2,
    ESCAPE124,
    DIRAC,
    BFI,
    CMV,
    MOTIONPIXELS,
    TGV,
    TGQ,
    TQI,
    AURA,
    AURA2,
    V210X,
    TMV,
    V210,
    DPX,
    MAD,
    FRWU,
    FLASHSV2,
    CDGRAPHICS,
    R210,
    ANM,
    BINKVIDEO,
    IFF_ILBM,
    IFF_BYTERUN1,
    KGV1,
    YOP,
    VP8,
    PICTOR,
    ANSI,
    A64_MULTI,
    A64_MULTI5,
    R10K,
    MXPEG,
    LAGARITH,
    PRORES,
    JV,
    DFA,
    WMV3IMAGE,
    VC1IMAGE,
    UTVIDEO,
    BMV_VIDEO,
    VBLE,
    DXTORY,
    V410,
    XWD,
    CDXL,
    XBM,
    ZEROCODEC,
    MSS1,
    MSA1,
    TSCC2,
    MTS2,
    CLLC,
    MSS2,
    VP9,
    AIC,
    ESCAPE130,
    G2M,
    WEBP,
    HNM4_VIDEO,
    HEVC,
    H265,
    FIC,
    ALIAS_PIX,
    BRENDER_PIX,
    PAF_VIDEO,
    EXR,
    VP7,
    SANM,
    SGIRLE,
    MVC1,
    MVC2,
    HQX,
    TDSC,
    HQ_HQA,
    HAP,
    DDS,
    DXV,
    SCREENPRESSO,
    RSCC,

    Y41P,
    AVRP,
    V012,
    AVUI,
    #[cfg(not(feature = "ffmpeg_7_0"))]
    AYUV,
    TARGA_Y216,
    V308,
    V408,
    YUV4,
    AVRN,
    CPIA,
    XFACE,
    SNOW,
    SMVJPEG,
    APNG,
    DAALA,
    CFHD,
    TRUEMOTION2RT,
    M101,
    MAGICYUV,
    SHEERVIDEO,
    YLC,

    // various PCM "codecs"
    PCM_S16LE,
    PCM_S16BE,
    PCM_U16LE,
    PCM_U16BE,
    PCM_S8,
    PCM_U8,
    PCM_MULAW,
    PCM_ALAW,
    PCM_S32LE,
    PCM_S32BE,
    PCM_U32LE,
    PCM_U32BE,
    PCM_S24LE,
    PCM_S24BE,
    PCM_U24LE,
    PCM_U24BE,
    PCM_S24DAUD,
    PCM_ZORK,
    PCM_S16LE_PLANAR,
    PCM_DVD,
    PCM_F32BE,
    PCM_F32LE,
    PCM_F64BE,
    PCM_F64LE,
    PCM_BLURAY,
    PCM_LXF,
    S302M,
    PCM_S8_PLANAR,
    PCM_S24LE_PLANAR,
    PCM_S32LE_PLANAR,
    PCM_S16BE_PLANAR,

    PCM_S64LE,
    PCM_S64BE,

    // various ADPCM codecs
    ADPCM_IMA_QT,
    ADPCM_IMA_WAV,
    ADPCM_IMA_DK3,
    ADPCM_IMA_DK4,
    ADPCM_IMA_WS,
    ADPCM_IMA_SMJPEG,
    ADPCM_MS,
    ADPCM_4XM,
    ADPCM_XA,
    ADPCM_ADX,
    ADPCM_EA,
    ADPCM_G726,
    ADPCM_CT,
    ADPCM_SWF,
    ADPCM_YAMAHA,
    ADPCM_SBPRO_4,
    ADPCM_SBPRO_3,
    ADPCM_SBPRO_2,
    ADPCM_THP,
    ADPCM_IMA_AMV,
    ADPCM_EA_R1,
    ADPCM_EA_R3,
    ADPCM_EA_R2,
    ADPCM_IMA_EA_SEAD,
    ADPCM_IMA_EA_EACS,
    ADPCM_EA_XAS,
    ADPCM_EA_MAXIS_XA,
    ADPCM_IMA_ISS,
    ADPCM_G722,
    ADPCM_IMA_APC,
    ADPCM_VIMA,

    ADPCM_AFC,
    ADPCM_IMA_OKI,
    ADPCM_DTK,
    ADPCM_IMA_RAD,
    ADPCM_G726LE,
    ADPCM_THP_LE,
    ADPCM_PSX,
    ADPCM_AICA,
    ADPCM_IMA_DAT4,
    ADPCM_MTAF,

    // AMR
    AMR_NB,
    AMR_WB,

    // RealAudio codecs
    RA_144,
    RA_288,

    // various DPCM codecs
    ROQ_DPCM,
    INTERPLAY_DPCM,
    XAN_DPCM,
    SOL_DPCM,

    SDX2_DPCM,

    // audio codecs
    MP2,
    MP3,
    AAC,
    AC3,
    DTS,
    VORBIS,
    DVAUDIO,
    WMAV1,
    WMAV2,
    MACE3,
    MACE6,
    VMDAUDIO,
    FLAC,
    MP3ADU,
    MP3ON4,
    SHORTEN,
    ALAC,
    WESTWOOD_SND1,
    GSM,
    QDM2,
    COOK,
    TRUESPEECH,
    TTA,
    SMACKAUDIO,
    QCELP,
    WAVPACK,
    DSICINAUDIO,
    IMC,
    MUSEPACK7,
    MLP,
    GSM_MS,
    ATRAC3,
    APE,
    NELLYMOSER,
    MUSEPACK8,
    SPEEX,
    WMAVOICE,
    WMAPRO,
    WMALOSSLESS,
    ATRAC3P,
    EAC3,
    SIPR,
    MP1,
    TWINVQ,
    TRUEHD,
    MP4ALS,
    ATRAC1,
    BINKAUDIO_RDFT,
    BINKAUDIO_DCT,
    AAC_LATM,
    QDMC,
    CELT,
    G723_1,
    G729,
    SVX_EXP8,
    SVX_FIB8,
    BMV_AUDIO,
    RALF,
    IAC,
    ILBC,
    OPUS,
    COMFORT_NOISE,
    TAK,
    METASOUND,
    PAF_AUDIO,
    ON2AVC,
    DSS_SP,

    CODEC2,
    FFWAVESYNTH,
    SONIC,
    SONIC_LS,
    EVRC,
    SMV,
    DSD_LSBF,
    DSD_MSBF,
    DSD_LSBF_PLANAR,
    DSD_MSBF_PLANAR,
    _4GV,
    INTERPLAY_ACM,
    XMA1,
    XMA2,
    DST,

    // subtitle codecs
    DVD_SUBTITLE,
    DVB_SUBTITLE,
    TEXT,
    XSUB,
    SSA,
    MOV_TEXT,
    HDMV_PGS_SUBTITLE,
    DVB_TELETEXT,
    SRT,

    MICRODVD,
    EIA_608,
    JACOSUB,
    SAMI,
    REALTEXT,
    STL,
    SUBVIEWER1,
    SUBVIEWER,
    SUBRIP,
    WEBVTT,
    MPL2,
    VPLAYER,
    PJS,
    ASS,
    HDMV_TEXT_SUBTITLE,

    // other specific kind of codecs (generally used for attachments)
    TTF,

    SCTE_35,
    BINTEXT,
    XBIN,
    IDF,
    OTF,
    SMPTE_KLV,
    DVD_NAV,
    TIMED_ID3,
    BIN_DATA,

    PROBE,

    MPEG2TS,
    MPEG4SYSTEMS,
    FFMETADATA,
    WRAPPED_AVFRAME,

    PSD,
    PIXLET,
    SPEEDHQ,
    CLEARVIDEO,
    FMVC,
    SCPR,
    XPM,
    AV1,
    PCM_F16LE,
    PCM_F24LE,
    ATRAC3AL,
    ATRAC3PAL,

    BITPACKED,
    MSCC,
    SRGC,
    SVG,
    GDV,
    FITS,
    GREMLIN_DPCM,
    DOLBY_E,

    APTX,
    APTX_HD,
    SBC,

    AVS2,
    IMM4,
    PROSUMER,
    MWSC,
    WCMV,
    RASC,
    PCM_VIDC,
    ATRAC9,
    TTML,

    HYMT,
    ARBC,
    AGM,
    LSCR,
    VP4,
    ADPCM_AGM,
    HCOM,
    ARIB_CAPTION,

    #[cfg(feature = "ffmpeg_4_3")]
    IMM5,
    #[cfg(feature = "ffmpeg_4_3")]
    MVDV,
    #[cfg(feature = "ffmpeg_4_3")]
    MVHA,
    #[cfg(feature = "ffmpeg_4_3")]
    CDTOONS,
    #[cfg(feature = "ffmpeg_4_3")]
    MV30,
    #[cfg(feature = "ffmpeg_4_3")]
    NOTCHLC,
    #[cfg(feature = "ffmpeg_4_3")]
    PFM,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_ARGO,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_SSI,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_ZORK,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_APM,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_ALP,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_MTF,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_CUNNING,
    #[cfg(feature = "ffmpeg_4_3")]
    DERF_DPCM,
    #[cfg(feature = "ffmpeg_4_3")]
    ACELP_KELVIN,
    #[cfg(feature = "ffmpeg_4_3")]
    MPEGH_3D_AUDIO,
    #[cfg(feature = "ffmpeg_4_3")]
    SIREN,
    #[cfg(feature = "ffmpeg_4_3")]
    HCA,
    #[cfg(feature = "ffmpeg_4_3")]
    EPG,

    #[cfg(feature = "ffmpeg_4_4")]
    AVS3,
    #[cfg(feature = "ffmpeg_4_4")]
    PGX,
    #[cfg(feature = "ffmpeg_4_4")]
    MSP2,
    #[cfg(feature = "ffmpeg_4_4")]
    VVC,
    #[cfg(feature = "ffmpeg_4_4")]
    MOBICLIP,
    #[cfg(feature = "ffmpeg_4_4")]
    PHOTOCD,
    #[cfg(feature = "ffmpeg_4_4")]
    ARGO,
    #[cfg(feature = "ffmpeg_4_4")]
    CRI,
    #[cfg(feature = "ffmpeg_4_4")]
    IPU,
    #[cfg(feature = "ffmpeg_4_4")]
    SIMBIOSIS_IMX,
    #[cfg(feature = "ffmpeg_4_4")]
    SGA_VIDEO,
    #[cfg(feature = "ffmpeg_4_4")]
    PCM_SGA,
    #[cfg(feature = "ffmpeg_4_4")]
    ADPCM_IMA_MOFLEX,
    #[cfg(feature = "ffmpeg_4_4")]
    FASTAUDIO,

    #[cfg(feature = "ffmpeg_5_0")]
    GEM,
    #[cfg(feature = "ffmpeg_5_0")]
    ADPCM_IMA_ACORN,
    #[cfg(feature = "ffmpeg_5_0")]
    MSNSIREN,

    #[cfg(feature = "ffmpeg_5_1")]
    VBN,
    #[cfg(feature = "ffmpeg_5_1")]
    JPEGXL,
    #[cfg(feature = "ffmpeg_5_1")]
    QOI,
    #[cfg(feature = "ffmpeg_5_1")]
    PHM,
    #[cfg(feature = "ffmpeg_5_1")]
    DFPWM,

    #[cfg(feature = "ffmpeg_6_0")]
    RADIANCE_HDR,
    #[cfg(feature = "ffmpeg_6_0")]
    WBMP,
    #[cfg(feature = "ffmpeg_6_0")]
    MEDIA100,
    #[cfg(feature = "ffmpeg_6_0")]
    VQC,
    #[cfg(feature = "ffmpeg_6_0")]
    ADPCM_XMD,
    #[cfg(feature = "ffmpeg_6_0")]
    WADY_DPCM,
    #[cfg(feature = "ffmpeg_6_0")]
    CBD2_DPCM,
    #[cfg(feature = "ffmpeg_6_0")]
    BONK,
    #[cfg(feature = "ffmpeg_6_0")]
    MISC4,
    #[cfg(feature = "ffmpeg_6_0")]
    APAC,
    #[cfg(feature = "ffmpeg_6_0")]
    FTR,
    #[cfg(feature = "ffmpeg_6_0")]
    WAVARC,
    #[cfg(feature = "ffmpeg_6_0")]
    RKA,
    #[cfg(feature = "ffmpeg_6_0")]
    VNULL,
    #[cfg(feature = "ffmpeg_6_0")]
    ANULL,

    #[cfg(feature = "ffmpeg_6_1")]
    PDV,
    #[cfg(feature = "ffmpeg_6_1")]
    EVC,
    #[cfg(feature = "ffmpeg_6_1")]
    RTV1,
    #[cfg(feature = "ffmpeg_6_1")]
    VMIX,
    #[cfg(feature = "ffmpeg_7_0")]
    LEAD,
    #[cfg(feature = "ffmpeg_6_1")]
    AC4,
    #[cfg(feature = "ffmpeg_6_1")]
    OSQ,
    #[cfg(feature = "ffmpeg_7_0")]
    QOA,
    #[cfg(feature = "ffmpeg_7_1")]
    LC3,
    #[cfg(feature = "ffmpeg_6_1")]
    SMPTE_2038,
    #[cfg(feature = "ffmpeg_7_1")]
    LCEVC,

    #[cfg(feature = "ffmpeg_8_0")]
    DNXUC,
    #[cfg(feature = "ffmpeg_8_0")]
    RV60,
    #[cfg(feature = "ffmpeg_8_0")]
    JPEGXL_ANIM,
    #[cfg(feature = "ffmpeg_8_0")]
    APV,
    #[cfg(feature = "ffmpeg_8_0")]
    PRORES_RAW,
    #[cfg(feature = "ffmpeg_8_0")]
    ADPCM_IMA_XBOX,
    #[cfg(feature = "ffmpeg_8_0")]
    ADPCM_SANYO,
    #[cfg(feature = "ffmpeg_8_0")]
    G728,
    #[cfg(feature = "ffmpeg_8_0")]
    IVTV_VBI,
    #[cfg(feature = "ffmpeg_8_0")]
    SMPTE_436M_ANC,
}

impl Id {
    pub fn medium(&self) -> media::Type {
        unsafe { media::Type::from(avcodec_get_type((*self).into())) }
    }

    pub fn name(&self) -> &'static str {
        unsafe { utils::str_from_c_ptr(avcodec_get_name((*self).into())) }
    }
}

impl From<AVCodecID> for Id {
    fn from(value: AVCodecID) -> Self {
        use AVCodecID as AV;

        match value {
            AV::NONE => Id::None,

            /* video codecs */
            AV::MPEG1VIDEO => Id::MPEG1VIDEO,
            AV::MPEG2VIDEO => Id::MPEG2VIDEO,
            #[cfg(all(feature = "ff_api_xvmc", not(feature = "ffmpeg_5_0")))]
            AV::MPEG2VIDEO_XVMC => Id::MPEG2VIDEO_XVMC,
            AV::H261 => Id::H261,
            AV::H263 => Id::H263,
            AV::RV10 => Id::RV10,
            AV::RV20 => Id::RV20,
            AV::MJPEG => Id::MJPEG,
            AV::MJPEGB => Id::MJPEGB,
            AV::LJPEG => Id::LJPEG,
            AV::SP5X => Id::SP5X,
            AV::JPEGLS => Id::JPEGLS,
            AV::MPEG4 => Id::MPEG4,
            AV::RAWVIDEO => Id::RAWVIDEO,
            AV::MSMPEG4V1 => Id::MSMPEG4V1,
            AV::MSMPEG4V2 => Id::MSMPEG4V2,
            AV::MSMPEG4V3 => Id::MSMPEG4V3,
            AV::WMV1 => Id::WMV1,
            AV::WMV2 => Id::WMV2,
            AV::H263P => Id::H263P,
            AV::H263I => Id::H263I,
            AV::FLV1 => Id::FLV1,
            AV::SVQ1 => Id::SVQ1,
            AV::SVQ3 => Id::SVQ3,
            AV::DVVIDEO => Id::DVVIDEO,
            AV::HUFFYUV => Id::HUFFYUV,
            AV::CYUV => Id::CYUV,
            AV::H264 => Id::H264,
            AV::INDEO3 => Id::INDEO3,
            AV::VP3 => Id::VP3,
            AV::THEORA => Id::THEORA,
            AV::ASV1 => Id::ASV1,
            AV::ASV2 => Id::ASV2,
            AV::FFV1 => Id::FFV1,
            AV::_4XM => Id::XM4,
            AV::VCR1 => Id::VCR1,
            AV::CLJR => Id::CLJR,
            AV::MDEC => Id::MDEC,
            AV::ROQ => Id::ROQ,
            AV::INTERPLAY_VIDEO => Id::INTERPLAY_VIDEO,
            AV::XAN_WC3 => Id::XAN_WC3,
            AV::XAN_WC4 => Id::XAN_WC4,
            AV::RPZA => Id::RPZA,
            AV::CINEPAK => Id::CINEPAK,
            AV::WS_VQA => Id::WS_VQA,
            AV::MSRLE => Id::MSRLE,
            AV::MSVIDEO1 => Id::MSVIDEO1,
            AV::IDCIN => Id::IDCIN,
            AV::_8BPS => Id::BPS8,
            AV::SMC => Id::SMC,
            AV::FLIC => Id::FLIC,
            AV::TRUEMOTION1 => Id::TRUEMOTION1,
            AV::VMDVIDEO => Id::VMDVIDEO,
            AV::MSZH => Id::MSZH,
            AV::ZLIB => Id::ZLIB,
            AV::QTRLE => Id::QTRLE,
            AV::TSCC => Id::TSCC,
            AV::ULTI => Id::ULTI,
            AV::QDRAW => Id::QDRAW,
            AV::VIXL => Id::VIXL,
            AV::QPEG => Id::QPEG,
            AV::PNG => Id::PNG,
            AV::PPM => Id::PPM,
            AV::PBM => Id::PBM,
            AV::PGM => Id::PGM,
            AV::PGMYUV => Id::PGMYUV,
            AV::PAM => Id::PAM,
            AV::FFVHUFF => Id::FFVHUFF,
            AV::RV30 => Id::RV30,
            AV::RV40 => Id::RV40,
            AV::VC1 => Id::VC1,
            AV::WMV3 => Id::WMV3,
            AV::LOCO => Id::LOCO,
            AV::WNV1 => Id::WNV1,
            AV::AASC => Id::AASC,
            AV::INDEO2 => Id::INDEO2,
            AV::FRAPS => Id::FRAPS,
            AV::TRUEMOTION2 => Id::TRUEMOTION2,
            AV::BMP => Id::BMP,
            AV::CSCD => Id::CSCD,
            AV::MMVIDEO => Id::MMVIDEO,
            AV::ZMBV => Id::ZMBV,
            AV::AVS => Id::AVS,
            AV::SMACKVIDEO => Id::SMACKVIDEO,
            AV::NUV => Id::NUV,
            AV::KMVC => Id::KMVC,
            AV::FLASHSV => Id::FLASHSV,
            AV::CAVS => Id::CAVS,
            AV::JPEG2000 => Id::JPEG2000,
            AV::VMNC => Id::VMNC,
            AV::VP5 => Id::VP5,
            AV::VP6 => Id::VP6,
            AV::VP6F => Id::VP6F,
            AV::TARGA => Id::TARGA,
            AV::DSICINVIDEO => Id::DSICINVIDEO,
            AV::TIERTEXSEQVIDEO => Id::TIERTEXSEQVIDEO,
            AV::TIFF => Id::TIFF,
            AV::GIF => Id::GIF,
            AV::DXA => Id::DXA,
            AV::DNXHD => Id::DNXHD,
            AV::THP => Id::THP,
            AV::SGI => Id::SGI,
            AV::C93 => Id::C93,
            AV::BETHSOFTVID => Id::BETHSOFTVID,
            AV::PTX => Id::PTX,
            AV::TXD => Id::TXD,
            AV::VP6A => Id::VP6A,
            AV::AMV => Id::AMV,
            AV::VB => Id::VB,
            AV::PCX => Id::PCX,
            AV::SUNRAST => Id::SUNRAST,
            AV::INDEO4 => Id::INDEO4,
            AV::INDEO5 => Id::INDEO5,
            AV::MIMIC => Id::MIMIC,
            AV::RL2 => Id::RL2,
            AV::ESCAPE124 => Id::ESCAPE124,
            AV::DIRAC => Id::DIRAC,
            AV::BFI => Id::BFI,
            AV::CMV => Id::CMV,
            AV::MOTIONPIXELS => Id::MOTIONPIXELS,
            AV::TGV => Id::TGV,
            AV::TGQ => Id::TGQ,
            AV::TQI => Id::TQI,
            AV::AURA => Id::AURA,
            AV::AURA2 => Id::AURA2,
            AV::V210X => Id::V210X,
            AV::TMV => Id::TMV,
            AV::V210 => Id::V210,
            AV::DPX => Id::DPX,
            AV::MAD => Id::MAD,
            AV::FRWU => Id::FRWU,
            AV::FLASHSV2 => Id::FLASHSV2,
            AV::CDGRAPHICS => Id::CDGRAPHICS,
            AV::R210 => Id::R210,
            AV::ANM => Id::ANM,
            AV::BINKVIDEO => Id::BINKVIDEO,
            AV::IFF_ILBM => Id::IFF_ILBM,
            AV::KGV1 => Id::KGV1,
            AV::YOP => Id::YOP,
            AV::VP8 => Id::VP8,
            AV::PICTOR => Id::PICTOR,
            AV::ANSI => Id::ANSI,
            AV::A64_MULTI => Id::A64_MULTI,
            AV::A64_MULTI5 => Id::A64_MULTI5,
            AV::R10K => Id::R10K,
            AV::MXPEG => Id::MXPEG,
            AV::LAGARITH => Id::LAGARITH,
            AV::PRORES => Id::PRORES,
            AV::JV => Id::JV,
            AV::DFA => Id::DFA,
            AV::WMV3IMAGE => Id::WMV3IMAGE,
            AV::VC1IMAGE => Id::VC1IMAGE,
            AV::UTVIDEO => Id::UTVIDEO,
            AV::BMV_VIDEO => Id::BMV_VIDEO,
            AV::VBLE => Id::VBLE,
            AV::DXTORY => Id::DXTORY,
            AV::V410 => Id::V410,
            AV::XWD => Id::XWD,
            AV::CDXL => Id::CDXL,
            AV::XBM => Id::XBM,
            AV::ZEROCODEC => Id::ZEROCODEC,
            AV::MSS1 => Id::MSS1,
            AV::MSA1 => Id::MSA1,
            AV::TSCC2 => Id::TSCC2,
            AV::MTS2 => Id::MTS2,
            AV::CLLC => Id::CLLC,
            AV::MSS2 => Id::MSS2,
            AV::VP9 => Id::VP9,
            AV::AIC => Id::AIC,
            AV::ESCAPE130 => Id::ESCAPE130,
            AV::G2M => Id::G2M,
            AV::WEBP => Id::WEBP,
            AV::HNM4_VIDEO => Id::HNM4_VIDEO,
            AV::HEVC => Id::HEVC,
            AV::FIC => Id::FIC,
            AV::ALIAS_PIX => Id::ALIAS_PIX,
            AV::BRENDER_PIX => Id::BRENDER_PIX,
            AV::PAF_VIDEO => Id::PAF_VIDEO,
            AV::EXR => Id::EXR,
            AV::VP7 => Id::VP7,
            AV::SANM => Id::SANM,
            AV::SGIRLE => Id::SGIRLE,
            AV::MVC1 => Id::MVC1,
            AV::MVC2 => Id::MVC2,
            AV::HQX => Id::HQX,
            AV::TDSC => Id::TDSC,
            AV::HQ_HQA => Id::HQ_HQA,
            AV::HAP => Id::HAP,
            AV::DDS => Id::DDS,
            AV::DXV => Id::DXV,
            AV::SCREENPRESSO => Id::SCREENPRESSO,
            AV::RSCC => Id::RSCC,

            AV::Y41P => Id::Y41P,
            AV::AVRP => Id::AVRP,
            AV::_012V => Id::V012,
            AV::AVUI => Id::AVUI,
            #[cfg(not(feature = "ffmpeg_7_0"))]
            AV::AYUV => Id::AYUV,
            AV::TARGA_Y216 => Id::TARGA_Y216,
            AV::V308 => Id::V308,
            AV::V408 => Id::V408,
            AV::YUV4 => Id::YUV4,
            AV::AVRN => Id::AVRN,
            AV::CPIA => Id::CPIA,
            AV::XFACE => Id::XFACE,
            AV::SNOW => Id::SNOW,
            AV::SMVJPEG => Id::SMVJPEG,
            AV::APNG => Id::APNG,
            AV::DAALA => Id::DAALA,
            AV::CFHD => Id::CFHD,
            AV::TRUEMOTION2RT => Id::TRUEMOTION2RT,
            AV::M101 => Id::M101,
            AV::MAGICYUV => Id::MAGICYUV,
            AV::SHEERVIDEO => Id::SHEERVIDEO,
            AV::YLC => Id::YLC,

            /* various PCM "codecs" */
            AV::PCM_S16LE => Id::PCM_S16LE,
            AV::PCM_S16BE => Id::PCM_S16BE,
            AV::PCM_U16LE => Id::PCM_U16LE,
            AV::PCM_U16BE => Id::PCM_U16BE,
            AV::PCM_S8 => Id::PCM_S8,
            AV::PCM_U8 => Id::PCM_U8,
            AV::PCM_MULAW => Id::PCM_MULAW,
            AV::PCM_ALAW => Id::PCM_ALAW,
            AV::PCM_S32LE => Id::PCM_S32LE,
            AV::PCM_S32BE => Id::PCM_S32BE,
            AV::PCM_U32LE => Id::PCM_U32LE,
            AV::PCM_U32BE => Id::PCM_U32BE,
            AV::PCM_S24LE => Id::PCM_S24LE,
            AV::PCM_S24BE => Id::PCM_S24BE,
            AV::PCM_U24LE => Id::PCM_U24LE,
            AV::PCM_U24BE => Id::PCM_U24BE,
            AV::PCM_S24DAUD => Id::PCM_S24DAUD,
            AV::PCM_ZORK => Id::PCM_ZORK,
            AV::PCM_S16LE_PLANAR => Id::PCM_S16LE_PLANAR,
            AV::PCM_DVD => Id::PCM_DVD,
            AV::PCM_F32BE => Id::PCM_F32BE,
            AV::PCM_F32LE => Id::PCM_F32LE,
            AV::PCM_F64BE => Id::PCM_F64BE,
            AV::PCM_F64LE => Id::PCM_F64LE,
            AV::PCM_BLURAY => Id::PCM_BLURAY,
            AV::PCM_LXF => Id::PCM_LXF,
            AV::S302M => Id::S302M,
            AV::PCM_S8_PLANAR => Id::PCM_S8_PLANAR,
            AV::PCM_S24LE_PLANAR => Id::PCM_S24LE_PLANAR,
            AV::PCM_S32LE_PLANAR => Id::PCM_S32LE_PLANAR,
            AV::PCM_S16BE_PLANAR => Id::PCM_S16BE_PLANAR,

            AV::PCM_S64LE => Id::PCM_S64LE,
            AV::PCM_S64BE => Id::PCM_S64BE,

            /* various ADPCM codecs */
            AV::ADPCM_IMA_QT => Id::ADPCM_IMA_QT,
            AV::ADPCM_IMA_WAV => Id::ADPCM_IMA_WAV,
            AV::ADPCM_IMA_DK3 => Id::ADPCM_IMA_DK3,
            AV::ADPCM_IMA_DK4 => Id::ADPCM_IMA_DK4,
            AV::ADPCM_IMA_WS => Id::ADPCM_IMA_WS,
            AV::ADPCM_IMA_SMJPEG => Id::ADPCM_IMA_SMJPEG,
            AV::ADPCM_MS => Id::ADPCM_MS,
            AV::ADPCM_4XM => Id::ADPCM_4XM,
            AV::ADPCM_XA => Id::ADPCM_XA,
            AV::ADPCM_ADX => Id::ADPCM_ADX,
            AV::ADPCM_EA => Id::ADPCM_EA,
            AV::ADPCM_G726 => Id::ADPCM_G726,
            AV::ADPCM_CT => Id::ADPCM_CT,
            AV::ADPCM_SWF => Id::ADPCM_SWF,
            AV::ADPCM_YAMAHA => Id::ADPCM_YAMAHA,
            AV::ADPCM_SBPRO_4 => Id::ADPCM_SBPRO_4,
            AV::ADPCM_SBPRO_3 => Id::ADPCM_SBPRO_3,
            AV::ADPCM_SBPRO_2 => Id::ADPCM_SBPRO_2,
            AV::ADPCM_THP => Id::ADPCM_THP,
            AV::ADPCM_IMA_AMV => Id::ADPCM_IMA_AMV,
            AV::ADPCM_EA_R1 => Id::ADPCM_EA_R1,
            AV::ADPCM_EA_R3 => Id::ADPCM_EA_R3,
            AV::ADPCM_EA_R2 => Id::ADPCM_EA_R2,
            AV::ADPCM_IMA_EA_SEAD => Id::ADPCM_IMA_EA_SEAD,
            AV::ADPCM_IMA_EA_EACS => Id::ADPCM_IMA_EA_EACS,
            AV::ADPCM_EA_XAS => Id::ADPCM_EA_XAS,
            AV::ADPCM_EA_MAXIS_XA => Id::ADPCM_EA_MAXIS_XA,
            AV::ADPCM_IMA_ISS => Id::ADPCM_IMA_ISS,
            AV::ADPCM_G722 => Id::ADPCM_G722,
            AV::ADPCM_IMA_APC => Id::ADPCM_IMA_APC,
            AV::ADPCM_VIMA => Id::ADPCM_VIMA,

            AV::ADPCM_AFC => Id::ADPCM_AFC,
            AV::ADPCM_IMA_OKI => Id::ADPCM_IMA_OKI,
            AV::ADPCM_DTK => Id::ADPCM_DTK,
            AV::ADPCM_IMA_RAD => Id::ADPCM_IMA_RAD,
            AV::ADPCM_G726LE => Id::ADPCM_G726LE,
            AV::ADPCM_THP_LE => Id::ADPCM_THP_LE,
            AV::ADPCM_PSX => Id::ADPCM_PSX,
            AV::ADPCM_AICA => Id::ADPCM_AICA,
            AV::ADPCM_IMA_DAT4 => Id::ADPCM_IMA_DAT4,
            AV::ADPCM_MTAF => Id::ADPCM_MTAF,

            /* AMR */
            AV::AMR_NB => Id::AMR_NB,
            AV::AMR_WB => Id::AMR_WB,

            /* RealAudio codecs*/
            AV::RA_144 => Id::RA_144,
            AV::RA_288 => Id::RA_288,

            /* various DPCM codecs */
            AV::ROQ_DPCM => Id::ROQ_DPCM,
            AV::INTERPLAY_DPCM => Id::INTERPLAY_DPCM,
            AV::XAN_DPCM => Id::XAN_DPCM,
            AV::SOL_DPCM => Id::SOL_DPCM,

            AV::SDX2_DPCM => Id::SDX2_DPCM,

            /* audio codecs */
            AV::MP2 => Id::MP2,
            AV::MP3 => Id::MP3,
            AV::AAC => Id::AAC,
            AV::AC3 => Id::AC3,
            AV::DTS => Id::DTS,
            AV::VORBIS => Id::VORBIS,
            AV::DVAUDIO => Id::DVAUDIO,
            AV::WMAV1 => Id::WMAV1,
            AV::WMAV2 => Id::WMAV2,
            AV::MACE3 => Id::MACE3,
            AV::MACE6 => Id::MACE6,
            AV::VMDAUDIO => Id::VMDAUDIO,
            AV::FLAC => Id::FLAC,
            AV::MP3ADU => Id::MP3ADU,
            AV::MP3ON4 => Id::MP3ON4,
            AV::SHORTEN => Id::SHORTEN,
            AV::ALAC => Id::ALAC,
            AV::WESTWOOD_SND1 => Id::WESTWOOD_SND1,
            AV::GSM => Id::GSM,
            AV::QDM2 => Id::QDM2,
            AV::COOK => Id::COOK,
            AV::TRUESPEECH => Id::TRUESPEECH,
            AV::TTA => Id::TTA,
            AV::SMACKAUDIO => Id::SMACKAUDIO,
            AV::QCELP => Id::QCELP,
            AV::WAVPACK => Id::WAVPACK,
            AV::DSICINAUDIO => Id::DSICINAUDIO,
            AV::IMC => Id::IMC,
            AV::MUSEPACK7 => Id::MUSEPACK7,
            AV::MLP => Id::MLP,
            AV::GSM_MS => Id::GSM_MS,
            AV::ATRAC3 => Id::ATRAC3,
            AV::APE => Id::APE,
            AV::NELLYMOSER => Id::NELLYMOSER,
            AV::MUSEPACK8 => Id::MUSEPACK8,
            AV::SPEEX => Id::SPEEX,
            AV::WMAVOICE => Id::WMAVOICE,
            AV::WMAPRO => Id::WMAPRO,
            AV::WMALOSSLESS => Id::WMALOSSLESS,
            AV::ATRAC3P => Id::ATRAC3P,
            AV::EAC3 => Id::EAC3,
            AV::SIPR => Id::SIPR,
            AV::MP1 => Id::MP1,
            AV::TWINVQ => Id::TWINVQ,
            AV::TRUEHD => Id::TRUEHD,
            AV::MP4ALS => Id::MP4ALS,
            AV::ATRAC1 => Id::ATRAC1,
            AV::BINKAUDIO_RDFT => Id::BINKAUDIO_RDFT,
            AV::BINKAUDIO_DCT => Id::BINKAUDIO_DCT,
            AV::AAC_LATM => Id::AAC_LATM,
            AV::QDMC => Id::QDMC,
            AV::CELT => Id::CELT,
            AV::G723_1 => Id::G723_1,
            AV::G729 => Id::G729,
            AV::_8SVX_EXP => Id::SVX_EXP8,
            AV::_8SVX_FIB => Id::SVX_FIB8,
            AV::BMV_AUDIO => Id::BMV_AUDIO,
            AV::RALF => Id::RALF,
            AV::IAC => Id::IAC,
            AV::ILBC => Id::ILBC,
            AV::OPUS => Id::OPUS,
            AV::COMFORT_NOISE => Id::COMFORT_NOISE,
            AV::TAK => Id::TAK,
            AV::METASOUND => Id::METASOUND,
            AV::PAF_AUDIO => Id::PAF_AUDIO,
            AV::ON2AVC => Id::ON2AVC,
            AV::DSS_SP => Id::DSS_SP,

            AV::CODEC2 => Id::CODEC2,
            AV::FFWAVESYNTH => Id::FFWAVESYNTH,
            AV::SONIC => Id::SONIC,
            AV::SONIC_LS => Id::SONIC_LS,
            AV::EVRC => Id::EVRC,
            AV::SMV => Id::SMV,
            AV::DSD_LSBF => Id::DSD_LSBF,
            AV::DSD_MSBF => Id::DSD_MSBF,
            AV::DSD_LSBF_PLANAR => Id::DSD_LSBF_PLANAR,
            AV::DSD_MSBF_PLANAR => Id::DSD_MSBF_PLANAR,
            AV::_4GV => Id::_4GV,
            AV::INTERPLAY_ACM => Id::INTERPLAY_ACM,
            AV::XMA1 => Id::XMA1,
            AV::XMA2 => Id::XMA2,
            AV::DST => Id::DST,

            /* subtitle codecs */
            AV::DVD_SUBTITLE => Id::DVD_SUBTITLE,
            AV::DVB_SUBTITLE => Id::DVB_SUBTITLE,
            AV::TEXT => Id::TEXT,
            AV::XSUB => Id::XSUB,
            AV::SSA => Id::SSA,
            AV::MOV_TEXT => Id::MOV_TEXT,
            AV::HDMV_PGS_SUBTITLE => Id::HDMV_PGS_SUBTITLE,
            AV::DVB_TELETEXT => Id::DVB_TELETEXT,
            AV::SRT => Id::SRT,

            AV::MICRODVD => Id::MICRODVD,
            AV::EIA_608 => Id::EIA_608,
            AV::JACOSUB => Id::JACOSUB,
            AV::SAMI => Id::SAMI,
            AV::REALTEXT => Id::REALTEXT,
            AV::STL => Id::STL,
            AV::SUBVIEWER1 => Id::SUBVIEWER1,
            AV::SUBVIEWER => Id::SUBVIEWER,
            AV::SUBRIP => Id::SUBRIP,
            AV::WEBVTT => Id::WEBVTT,
            AV::MPL2 => Id::MPL2,
            AV::VPLAYER => Id::VPLAYER,
            AV::PJS => Id::PJS,
            AV::ASS => Id::ASS,
            AV::HDMV_TEXT_SUBTITLE => Id::HDMV_TEXT_SUBTITLE,

            /* other specific kind of codecs (generally used for attachments) */
            AV::TTF => Id::TTF,

            AV::SCTE_35 => Id::SCTE_35,
            AV::BINTEXT => Id::BINTEXT,
            AV::XBIN => Id::XBIN,
            AV::IDF => Id::IDF,
            AV::OTF => Id::OTF,
            AV::SMPTE_KLV => Id::SMPTE_KLV,
            AV::DVD_NAV => Id::DVD_NAV,
            AV::TIMED_ID3 => Id::TIMED_ID3,
            AV::BIN_DATA => Id::BIN_DATA,

            AV::PROBE => Id::PROBE,

            AV::MPEG2TS => Id::MPEG2TS,
            AV::MPEG4SYSTEMS => Id::MPEG4SYSTEMS,
            AV::FFMETADATA => Id::FFMETADATA,
            AV::WRAPPED_AVFRAME => Id::WRAPPED_AVFRAME,
            AV::PSD => Id::PSD,
            AV::PIXLET => Id::PIXLET,
            AV::SPEEDHQ => Id::SPEEDHQ,
            AV::CLEARVIDEO => Id::CLEARVIDEO,
            AV::FMVC => Id::FMVC,
            AV::SCPR => Id::SCPR,
            AV::XPM => Id::XPM,
            AV::AV1 => Id::AV1,
            AV::PCM_F16LE => Id::PCM_F16LE,
            AV::PCM_F24LE => Id::PCM_F24LE,
            AV::ATRAC3AL => Id::ATRAC3AL,
            AV::ATRAC3PAL => Id::ATRAC3PAL,

            AV::BITPACKED => Id::BITPACKED,
            AV::MSCC => Id::MSCC,
            AV::SRGC => Id::SRGC,
            AV::SVG => Id::SVG,
            AV::GDV => Id::GDV,
            AV::FITS => Id::FITS,
            AV::GREMLIN_DPCM => Id::GREMLIN_DPCM,
            AV::DOLBY_E => Id::DOLBY_E,

            AV::APTX => Id::APTX,
            AV::APTX_HD => Id::APTX_HD,
            AV::SBC => Id::SBC,

            AV::AVS2 => Id::AVS2,
            AV::IMM4 => Id::IMM4,
            AV::PROSUMER => Id::PROSUMER,
            AV::MWSC => Id::MWSC,
            AV::WCMV => Id::WCMV,
            AV::RASC => Id::RASC,
            AV::PCM_VIDC => Id::PCM_VIDC,
            AV::ATRAC9 => Id::ATRAC9,
            AV::TTML => Id::TTML,

            AV::HYMT => Id::HYMT,
            AV::ARBC => Id::ARBC,
            AV::AGM => Id::AGM,
            AV::LSCR => Id::LSCR,
            AV::VP4 => Id::VP4,
            AV::ADPCM_AGM => Id::ADPCM_AGM,
            AV::HCOM => Id::HCOM,
            AV::ARIB_CAPTION => Id::ARIB_CAPTION,

            #[cfg(feature = "ffmpeg_4_3")]
            AV::IMM5 => Id::IMM5,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::MVDV => Id::MVDV,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::MVHA => Id::MVHA,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::CDTOONS => Id::CDTOONS,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::MV30 => Id::MV30,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::NOTCHLC => Id::NOTCHLC,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::PFM => Id::PFM,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_ARGO => Id::ADPCM_ARGO,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_IMA_SSI => Id::ADPCM_IMA_SSI,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_ZORK => Id::ADPCM_ZORK,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_IMA_APM => Id::ADPCM_IMA_APM,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_IMA_ALP => Id::ADPCM_IMA_ALP,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_IMA_MTF => Id::ADPCM_IMA_MTF,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ADPCM_IMA_CUNNING => Id::ADPCM_IMA_CUNNING,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::DERF_DPCM => Id::DERF_DPCM,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::ACELP_KELVIN => Id::ACELP_KELVIN,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::MPEGH_3D_AUDIO => Id::MPEGH_3D_AUDIO,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::SIREN => Id::SIREN,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::HCA => Id::HCA,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::EPG => Id::EPG,

            #[cfg(feature = "ffmpeg_4_4")]
            AV::PGX => Id::PGX,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AVS3 => Id::AVS3,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::MSP2 => Id::MSP2,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::VVC => Id::VVC,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::MOBICLIP => Id::MOBICLIP,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::PHOTOCD => Id::PHOTOCD,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::IPU => Id::IPU,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::ARGO => Id::ARGO,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::CRI => Id::CRI,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::SIMBIOSIS_IMX => Id::SIMBIOSIS_IMX,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::SGA_VIDEO => Id::SGA_VIDEO,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::PCM_SGA => Id::PCM_SGA,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::ADPCM_IMA_MOFLEX => Id::ADPCM_IMA_MOFLEX,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::FASTAUDIO => Id::FASTAUDIO,

            #[cfg(feature = "ffmpeg_5_0")]
            AV::GEM => Id::GEM,
            #[cfg(feature = "ffmpeg_5_0")]
            AV::ADPCM_IMA_ACORN => Id::ADPCM_IMA_ACORN,
            #[cfg(feature = "ffmpeg_5_0")]
            AV::MSNSIREN => Id::MSNSIREN,

            #[cfg(feature = "ffmpeg_5_1")]
            AV::VBN => Id::VBN,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::JPEGXL => Id::JPEGXL,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::QOI => Id::QOI,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::PHM => Id::PHM,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::DFPWM => Id::DFPWM,

            #[cfg(feature = "ffmpeg_6_0")]
            AV::RADIANCE_HDR => Id::RADIANCE_HDR,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::WBMP => Id::WBMP,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::MEDIA100 => Id::MEDIA100,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::VQC => Id::VQC,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::ADPCM_XMD => Id::ADPCM_XMD,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::WADY_DPCM => Id::WADY_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::CBD2_DPCM => Id::CBD2_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::BONK => Id::BONK,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::MISC4 => Id::MISC4,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::APAC => Id::APAC,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::FTR => Id::FTR,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::WAVARC => Id::WAVARC,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::RKA => Id::RKA,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::VNULL => Id::VNULL,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::ANULL => Id::ANULL,

            #[cfg(feature = "ffmpeg_6_1")]
            AV::PDV => Id::PDV,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::EVC => Id::EVC,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::RTV1 => Id::RTV1,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::VMIX => Id::VMIX,
            #[cfg(feature = "ffmpeg_7_0")]
            AV::LEAD => Id::LEAD,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AC4 => Id::AC4,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::OSQ => Id::OSQ,
            #[cfg(feature = "ffmpeg_7_0")]
            AV::QOA => Id::QOA,
            #[cfg(feature = "ffmpeg_7_1")]
            AV::LC3 => Id::LC3,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::SMPTE_2038 => Id::SMPTE_2038,
            #[cfg(feature = "ffmpeg_7_1")]
            AV::LCEVC => Id::LCEVC,

            #[cfg(feature = "ffmpeg_8_0")]
            AV::DNXUC => Id::DNXUC,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::RV60 => Id::RV60,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::JPEGXL_ANIM => Id::JPEGXL_ANIM,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::APV => Id::APV,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::PRORES_RAW => Id::PRORES_RAW,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::ADPCM_IMA_XBOX => Id::ADPCM_IMA_XBOX,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::ADPCM_SANYO => Id::ADPCM_SANYO,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::G728 => Id::G728,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::IVTV_VBI => Id::IVTV_VBI,
            #[cfg(feature = "ffmpeg_8_0")]
            AV::SMPTE_436M_ANC => Id::SMPTE_436M_ANC,

            _ => unimplemented!(),
        }
    }
}

impl From<Id> for AVCodecID {
    fn from(value: Id) -> AVCodecID {
        use AVCodecID as AV;

        match value {
            Id::None => AV::NONE,

            /* video codecs */
            Id::MPEG1VIDEO => AV::MPEG1VIDEO,
            Id::MPEG2VIDEO => AV::MPEG2VIDEO,
            #[cfg(all(feature = "ff_api_xvmc", not(feature = "ffmpeg_5_0")))]
            Id::MPEG2VIDEO_XVMC => AV::MPEG2VIDEO_XVMC,
            Id::H261 => AV::H261,
            Id::H263 => AV::H263,
            Id::RV10 => AV::RV10,
            Id::RV20 => AV::RV20,
            Id::MJPEG => AV::MJPEG,
            Id::MJPEGB => AV::MJPEGB,
            Id::LJPEG => AV::LJPEG,
            Id::SP5X => AV::SP5X,
            Id::JPEGLS => AV::JPEGLS,
            Id::MPEG4 => AV::MPEG4,
            Id::RAWVIDEO => AV::RAWVIDEO,
            Id::MSMPEG4V1 => AV::MSMPEG4V1,
            Id::MSMPEG4V2 => AV::MSMPEG4V2,
            Id::MSMPEG4V3 => AV::MSMPEG4V3,
            Id::WMV1 => AV::WMV1,
            Id::WMV2 => AV::WMV2,
            Id::H263P => AV::H263P,
            Id::H263I => AV::H263I,
            Id::FLV1 => AV::FLV1,
            Id::SVQ1 => AV::SVQ1,
            Id::SVQ3 => AV::SVQ3,
            Id::DVVIDEO => AV::DVVIDEO,
            Id::HUFFYUV => AV::HUFFYUV,
            Id::CYUV => AV::CYUV,
            Id::H264 => AV::H264,
            Id::INDEO3 => AV::INDEO3,
            Id::VP3 => AV::VP3,
            Id::THEORA => AV::THEORA,
            Id::ASV1 => AV::ASV1,
            Id::ASV2 => AV::ASV2,
            Id::FFV1 => AV::FFV1,
            Id::XM4 => AV::_4XM,
            Id::VCR1 => AV::VCR1,
            Id::CLJR => AV::CLJR,
            Id::MDEC => AV::MDEC,
            Id::ROQ => AV::ROQ,
            Id::INTERPLAY_VIDEO => AV::INTERPLAY_VIDEO,
            Id::XAN_WC3 => AV::XAN_WC3,
            Id::XAN_WC4 => AV::XAN_WC4,
            Id::RPZA => AV::RPZA,
            Id::CINEPAK => AV::CINEPAK,
            Id::WS_VQA => AV::WS_VQA,
            Id::MSRLE => AV::MSRLE,
            Id::MSVIDEO1 => AV::MSVIDEO1,
            Id::IDCIN => AV::IDCIN,
            Id::BPS8 => AV::_8BPS,
            Id::SMC => AV::SMC,
            Id::FLIC => AV::FLIC,
            Id::TRUEMOTION1 => AV::TRUEMOTION1,
            Id::VMDVIDEO => AV::VMDVIDEO,
            Id::MSZH => AV::MSZH,
            Id::ZLIB => AV::ZLIB,
            Id::QTRLE => AV::QTRLE,
            Id::TSCC => AV::TSCC,
            Id::ULTI => AV::ULTI,
            Id::QDRAW => AV::QDRAW,
            Id::VIXL => AV::VIXL,
            Id::QPEG => AV::QPEG,
            Id::PNG => AV::PNG,
            Id::PPM => AV::PPM,
            Id::PBM => AV::PBM,
            Id::PGM => AV::PGM,
            Id::PGMYUV => AV::PGMYUV,
            Id::PAM => AV::PAM,
            Id::FFVHUFF => AV::FFVHUFF,
            Id::RV30 => AV::RV30,
            Id::RV40 => AV::RV40,
            Id::VC1 => AV::VC1,
            Id::WMV3 => AV::WMV3,
            Id::LOCO => AV::LOCO,
            Id::WNV1 => AV::WNV1,
            Id::AASC => AV::AASC,
            Id::INDEO2 => AV::INDEO2,
            Id::FRAPS => AV::FRAPS,
            Id::TRUEMOTION2 => AV::TRUEMOTION2,
            Id::BMP => AV::BMP,
            Id::CSCD => AV::CSCD,
            Id::MMVIDEO => AV::MMVIDEO,
            Id::ZMBV => AV::ZMBV,
            Id::AVS => AV::AVS,
            Id::SMACKVIDEO => AV::SMACKVIDEO,
            Id::NUV => AV::NUV,
            Id::KMVC => AV::KMVC,
            Id::FLASHSV => AV::FLASHSV,
            Id::CAVS => AV::CAVS,
            Id::JPEG2000 => AV::JPEG2000,
            Id::VMNC => AV::VMNC,
            Id::VP5 => AV::VP5,
            Id::VP6 => AV::VP6,
            Id::VP6F => AV::VP6F,
            Id::TARGA => AV::TARGA,
            Id::DSICINVIDEO => AV::DSICINVIDEO,
            Id::TIERTEXSEQVIDEO => AV::TIERTEXSEQVIDEO,
            Id::TIFF => AV::TIFF,
            Id::GIF => AV::GIF,
            Id::DXA => AV::DXA,
            Id::DNXHD => AV::DNXHD,
            Id::THP => AV::THP,
            Id::SGI => AV::SGI,
            Id::C93 => AV::C93,
            Id::BETHSOFTVID => AV::BETHSOFTVID,
            Id::PTX => AV::PTX,
            Id::TXD => AV::TXD,
            Id::VP6A => AV::VP6A,
            Id::AMV => AV::AMV,
            Id::VB => AV::VB,
            Id::PCX => AV::PCX,
            Id::SUNRAST => AV::SUNRAST,
            Id::INDEO4 => AV::INDEO4,
            Id::INDEO5 => AV::INDEO5,
            Id::MIMIC => AV::MIMIC,
            Id::RL2 => AV::RL2,
            Id::ESCAPE124 => AV::ESCAPE124,
            Id::DIRAC => AV::DIRAC,
            Id::BFI => AV::BFI,
            Id::CMV => AV::CMV,
            Id::MOTIONPIXELS => AV::MOTIONPIXELS,
            Id::TGV => AV::TGV,
            Id::TGQ => AV::TGQ,
            Id::TQI => AV::TQI,
            Id::AURA => AV::AURA,
            Id::AURA2 => AV::AURA2,
            Id::V210X => AV::V210X,
            Id::TMV => AV::TMV,
            Id::V210 => AV::V210,
            Id::DPX => AV::DPX,
            Id::MAD => AV::MAD,
            Id::FRWU => AV::FRWU,
            Id::FLASHSV2 => AV::FLASHSV2,
            Id::CDGRAPHICS => AV::CDGRAPHICS,
            Id::R210 => AV::R210,
            Id::ANM => AV::ANM,
            Id::BINKVIDEO => AV::BINKVIDEO,
            Id::IFF_ILBM => AV::IFF_ILBM,
            Id::IFF_BYTERUN1 => AV::IFF_ILBM,
            Id::KGV1 => AV::KGV1,
            Id::YOP => AV::YOP,
            Id::VP8 => AV::VP8,
            Id::PICTOR => AV::PICTOR,
            Id::ANSI => AV::ANSI,
            Id::A64_MULTI => AV::A64_MULTI,
            Id::A64_MULTI5 => AV::A64_MULTI5,
            Id::R10K => AV::R10K,
            Id::MXPEG => AV::MXPEG,
            Id::LAGARITH => AV::LAGARITH,
            Id::PRORES => AV::PRORES,
            Id::JV => AV::JV,
            Id::DFA => AV::DFA,
            Id::WMV3IMAGE => AV::WMV3IMAGE,
            Id::VC1IMAGE => AV::VC1IMAGE,
            Id::UTVIDEO => AV::UTVIDEO,
            Id::BMV_VIDEO => AV::BMV_VIDEO,
            Id::VBLE => AV::VBLE,
            Id::DXTORY => AV::DXTORY,
            Id::V410 => AV::V410,
            Id::XWD => AV::XWD,
            Id::CDXL => AV::CDXL,
            Id::XBM => AV::XBM,
            Id::ZEROCODEC => AV::ZEROCODEC,
            Id::MSS1 => AV::MSS1,
            Id::MSA1 => AV::MSA1,
            Id::TSCC2 => AV::TSCC2,
            Id::MTS2 => AV::MTS2,
            Id::CLLC => AV::CLLC,
            Id::MSS2 => AV::MSS2,
            Id::VP9 => AV::VP9,
            Id::AIC => AV::AIC,
            Id::ESCAPE130 => AV::ESCAPE130,
            Id::G2M => AV::G2M,
            Id::WEBP => AV::WEBP,
            Id::HNM4_VIDEO => AV::HNM4_VIDEO,
            Id::HEVC => AV::HEVC,
            Id::H265 => AV::HEVC,
            Id::FIC => AV::FIC,
            Id::ALIAS_PIX => AV::ALIAS_PIX,
            Id::BRENDER_PIX => AV::BRENDER_PIX,
            Id::PAF_VIDEO => AV::PAF_VIDEO,
            Id::EXR => AV::EXR,
            Id::VP7 => AV::VP7,
            Id::SANM => AV::SANM,
            Id::SGIRLE => AV::SGIRLE,
            Id::MVC1 => AV::MVC1,
            Id::MVC2 => AV::MVC2,
            Id::HQX => AV::HQX,
            Id::TDSC => AV::TDSC,
            Id::HQ_HQA => AV::HQ_HQA,
            Id::HAP => AV::HAP,
            Id::DDS => AV::DDS,
            Id::DXV => AV::DXV,
            Id::SCREENPRESSO => AV::SCREENPRESSO,
            Id::RSCC => AV::RSCC,

            Id::Y41P => AV::Y41P,
            Id::AVRP => AV::AVRP,
            Id::V012 => AV::_012V,
            Id::AVUI => AV::AVUI,
            #[cfg(not(feature = "ffmpeg_7_0"))]
            Id::AYUV => AV::AYUV,
            Id::TARGA_Y216 => AV::TARGA_Y216,
            Id::V308 => AV::V308,
            Id::V408 => AV::V408,
            Id::YUV4 => AV::YUV4,
            Id::AVRN => AV::AVRN,
            Id::CPIA => AV::CPIA,
            Id::XFACE => AV::XFACE,
            Id::SNOW => AV::SNOW,
            Id::SMVJPEG => AV::SMVJPEG,
            Id::APNG => AV::APNG,
            Id::DAALA => AV::DAALA,
            Id::CFHD => AV::CFHD,
            Id::TRUEMOTION2RT => AV::TRUEMOTION2RT,
            Id::M101 => AV::M101,
            Id::MAGICYUV => AV::MAGICYUV,
            Id::SHEERVIDEO => AV::SHEERVIDEO,
            Id::YLC => AV::YLC,

            /* various PCM "codecs" */
            Id::PCM_S16LE => AV::PCM_S16LE,
            Id::PCM_S16BE => AV::PCM_S16BE,
            Id::PCM_U16LE => AV::PCM_U16LE,
            Id::PCM_U16BE => AV::PCM_U16BE,
            Id::PCM_S8 => AV::PCM_S8,
            Id::PCM_U8 => AV::PCM_U8,
            Id::PCM_MULAW => AV::PCM_MULAW,
            Id::PCM_ALAW => AV::PCM_ALAW,
            Id::PCM_S32LE => AV::PCM_S32LE,
            Id::PCM_S32BE => AV::PCM_S32BE,
            Id::PCM_U32LE => AV::PCM_U32LE,
            Id::PCM_U32BE => AV::PCM_U32BE,
            Id::PCM_S24LE => AV::PCM_S24LE,
            Id::PCM_S24BE => AV::PCM_S24BE,
            Id::PCM_U24LE => AV::PCM_U24LE,
            Id::PCM_U24BE => AV::PCM_U24BE,
            Id::PCM_S24DAUD => AV::PCM_S24DAUD,
            Id::PCM_ZORK => AV::PCM_ZORK,
            Id::PCM_S16LE_PLANAR => AV::PCM_S16LE_PLANAR,
            Id::PCM_DVD => AV::PCM_DVD,
            Id::PCM_F32BE => AV::PCM_F32BE,
            Id::PCM_F32LE => AV::PCM_F32LE,
            Id::PCM_F64BE => AV::PCM_F64BE,
            Id::PCM_F64LE => AV::PCM_F64LE,
            Id::PCM_BLURAY => AV::PCM_BLURAY,
            Id::PCM_LXF => AV::PCM_LXF,
            Id::S302M => AV::S302M,
            Id::PCM_S8_PLANAR => AV::PCM_S8_PLANAR,
            Id::PCM_S24LE_PLANAR => AV::PCM_S24LE_PLANAR,
            Id::PCM_S32LE_PLANAR => AV::PCM_S32LE_PLANAR,
            Id::PCM_S16BE_PLANAR => AV::PCM_S16BE_PLANAR,

            Id::PCM_S64LE => AV::PCM_S64LE,
            Id::PCM_S64BE => AV::PCM_S64BE,

            /* various ADPCM codecs */
            Id::ADPCM_IMA_QT => AV::ADPCM_IMA_QT,
            Id::ADPCM_IMA_WAV => AV::ADPCM_IMA_WAV,
            Id::ADPCM_IMA_DK3 => AV::ADPCM_IMA_DK3,
            Id::ADPCM_IMA_DK4 => AV::ADPCM_IMA_DK4,
            Id::ADPCM_IMA_WS => AV::ADPCM_IMA_WS,
            Id::ADPCM_IMA_SMJPEG => AV::ADPCM_IMA_SMJPEG,
            Id::ADPCM_MS => AV::ADPCM_MS,
            Id::ADPCM_4XM => AV::ADPCM_4XM,
            Id::ADPCM_XA => AV::ADPCM_XA,
            Id::ADPCM_ADX => AV::ADPCM_ADX,
            Id::ADPCM_EA => AV::ADPCM_EA,
            Id::ADPCM_G726 => AV::ADPCM_G726,
            Id::ADPCM_CT => AV::ADPCM_CT,
            Id::ADPCM_SWF => AV::ADPCM_SWF,
            Id::ADPCM_YAMAHA => AV::ADPCM_YAMAHA,
            Id::ADPCM_SBPRO_4 => AV::ADPCM_SBPRO_4,
            Id::ADPCM_SBPRO_3 => AV::ADPCM_SBPRO_3,
            Id::ADPCM_SBPRO_2 => AV::ADPCM_SBPRO_2,
            Id::ADPCM_THP => AV::ADPCM_THP,
            Id::ADPCM_IMA_AMV => AV::ADPCM_IMA_AMV,
            Id::ADPCM_EA_R1 => AV::ADPCM_EA_R1,
            Id::ADPCM_EA_R3 => AV::ADPCM_EA_R3,
            Id::ADPCM_EA_R2 => AV::ADPCM_EA_R2,
            Id::ADPCM_IMA_EA_SEAD => AV::ADPCM_IMA_EA_SEAD,
            Id::ADPCM_IMA_EA_EACS => AV::ADPCM_IMA_EA_EACS,
            Id::ADPCM_EA_XAS => AV::ADPCM_EA_XAS,
            Id::ADPCM_EA_MAXIS_XA => AV::ADPCM_EA_MAXIS_XA,
            Id::ADPCM_IMA_ISS => AV::ADPCM_IMA_ISS,
            Id::ADPCM_G722 => AV::ADPCM_G722,
            Id::ADPCM_IMA_APC => AV::ADPCM_IMA_APC,
            Id::ADPCM_VIMA => AV::ADPCM_VIMA,

            Id::ADPCM_AFC => AV::ADPCM_AFC,
            Id::ADPCM_IMA_OKI => AV::ADPCM_IMA_OKI,
            Id::ADPCM_DTK => AV::ADPCM_DTK,
            Id::ADPCM_IMA_RAD => AV::ADPCM_IMA_RAD,
            Id::ADPCM_G726LE => AV::ADPCM_G726LE,
            Id::ADPCM_THP_LE => AV::ADPCM_THP_LE,
            Id::ADPCM_PSX => AV::ADPCM_PSX,
            Id::ADPCM_AICA => AV::ADPCM_AICA,
            Id::ADPCM_IMA_DAT4 => AV::ADPCM_IMA_DAT4,
            Id::ADPCM_MTAF => AV::ADPCM_MTAF,

            /* AMR */
            Id::AMR_NB => AV::AMR_NB,
            Id::AMR_WB => AV::AMR_WB,

            /* RealAudio codecs*/
            Id::RA_144 => AV::RA_144,
            Id::RA_288 => AV::RA_288,

            /* various DPCM codecs */
            Id::ROQ_DPCM => AV::ROQ_DPCM,
            Id::INTERPLAY_DPCM => AV::INTERPLAY_DPCM,
            Id::XAN_DPCM => AV::XAN_DPCM,
            Id::SOL_DPCM => AV::SOL_DPCM,

            Id::SDX2_DPCM => AV::SDX2_DPCM,

            /* audio codecs */
            Id::MP2 => AV::MP2,
            Id::MP3 => AV::MP3,
            Id::AAC => AV::AAC,
            Id::AC3 => AV::AC3,
            Id::DTS => AV::DTS,
            Id::VORBIS => AV::VORBIS,
            Id::DVAUDIO => AV::DVAUDIO,
            Id::WMAV1 => AV::WMAV1,
            Id::WMAV2 => AV::WMAV2,
            Id::MACE3 => AV::MACE3,
            Id::MACE6 => AV::MACE6,
            Id::VMDAUDIO => AV::VMDAUDIO,
            Id::FLAC => AV::FLAC,
            Id::MP3ADU => AV::MP3ADU,
            Id::MP3ON4 => AV::MP3ON4,
            Id::SHORTEN => AV::SHORTEN,
            Id::ALAC => AV::ALAC,
            Id::WESTWOOD_SND1 => AV::WESTWOOD_SND1,
            Id::GSM => AV::GSM,
            Id::QDM2 => AV::QDM2,
            Id::COOK => AV::COOK,
            Id::TRUESPEECH => AV::TRUESPEECH,
            Id::TTA => AV::TTA,
            Id::SMACKAUDIO => AV::SMACKAUDIO,
            Id::QCELP => AV::QCELP,
            Id::WAVPACK => AV::WAVPACK,
            Id::DSICINAUDIO => AV::DSICINAUDIO,
            Id::IMC => AV::IMC,
            Id::MUSEPACK7 => AV::MUSEPACK7,
            Id::MLP => AV::MLP,
            Id::GSM_MS => AV::GSM_MS,
            Id::ATRAC3 => AV::ATRAC3,
            Id::APE => AV::APE,
            Id::NELLYMOSER => AV::NELLYMOSER,
            Id::MUSEPACK8 => AV::MUSEPACK8,
            Id::SPEEX => AV::SPEEX,
            Id::WMAVOICE => AV::WMAVOICE,
            Id::WMAPRO => AV::WMAPRO,
            Id::WMALOSSLESS => AV::WMALOSSLESS,
            Id::ATRAC3P => AV::ATRAC3P,
            Id::EAC3 => AV::EAC3,
            Id::SIPR => AV::SIPR,
            Id::MP1 => AV::MP1,
            Id::TWINVQ => AV::TWINVQ,
            Id::TRUEHD => AV::TRUEHD,
            Id::MP4ALS => AV::MP4ALS,
            Id::ATRAC1 => AV::ATRAC1,
            Id::BINKAUDIO_RDFT => AV::BINKAUDIO_RDFT,
            Id::BINKAUDIO_DCT => AV::BINKAUDIO_DCT,
            Id::AAC_LATM => AV::AAC_LATM,
            Id::QDMC => AV::QDMC,
            Id::CELT => AV::CELT,
            Id::G723_1 => AV::G723_1,
            Id::G729 => AV::G729,
            Id::SVX_EXP8 => AV::_8SVX_EXP,
            Id::SVX_FIB8 => AV::_8SVX_FIB,
            Id::BMV_AUDIO => AV::BMV_AUDIO,
            Id::RALF => AV::RALF,
            Id::IAC => AV::IAC,
            Id::ILBC => AV::ILBC,
            Id::OPUS => AV::OPUS,
            Id::COMFORT_NOISE => AV::COMFORT_NOISE,
            Id::TAK => AV::TAK,
            Id::METASOUND => AV::METASOUND,
            Id::PAF_AUDIO => AV::PAF_AUDIO,
            Id::ON2AVC => AV::ON2AVC,
            Id::DSS_SP => AV::DSS_SP,

            Id::CODEC2 => AV::CODEC2,
            Id::FFWAVESYNTH => AV::FFWAVESYNTH,
            Id::SONIC => AV::SONIC,
            Id::SONIC_LS => AV::SONIC_LS,
            Id::EVRC => AV::EVRC,
            Id::SMV => AV::SMV,
            Id::DSD_LSBF => AV::DSD_LSBF,
            Id::DSD_MSBF => AV::DSD_MSBF,
            Id::DSD_LSBF_PLANAR => AV::DSD_LSBF_PLANAR,
            Id::DSD_MSBF_PLANAR => AV::DSD_MSBF_PLANAR,
            Id::_4GV => AV::_4GV,
            Id::INTERPLAY_ACM => AV::INTERPLAY_ACM,
            Id::XMA1 => AV::XMA1,
            Id::XMA2 => AV::XMA2,
            Id::DST => AV::DST,

            /* subtitle codecs */
            Id::DVD_SUBTITLE => AV::DVD_SUBTITLE,
            Id::DVB_SUBTITLE => AV::DVB_SUBTITLE,
            Id::TEXT => AV::TEXT,
            Id::XSUB => AV::XSUB,
            Id::SSA => AV::SSA,
            Id::MOV_TEXT => AV::MOV_TEXT,
            Id::HDMV_PGS_SUBTITLE => AV::HDMV_PGS_SUBTITLE,
            Id::DVB_TELETEXT => AV::DVB_TELETEXT,
            Id::SRT => AV::SRT,

            Id::MICRODVD => AV::MICRODVD,
            Id::EIA_608 => AV::EIA_608,
            Id::JACOSUB => AV::JACOSUB,
            Id::SAMI => AV::SAMI,
            Id::REALTEXT => AV::REALTEXT,
            Id::STL => AV::STL,
            Id::SUBVIEWER1 => AV::SUBVIEWER1,
            Id::SUBVIEWER => AV::SUBVIEWER,
            Id::SUBRIP => AV::SUBRIP,
            Id::WEBVTT => AV::WEBVTT,
            Id::MPL2 => AV::MPL2,
            Id::VPLAYER => AV::VPLAYER,
            Id::PJS => AV::PJS,
            Id::ASS => AV::ASS,
            Id::HDMV_TEXT_SUBTITLE => AV::HDMV_TEXT_SUBTITLE,

            /* other specific kind of codecs (generally used for attachments) */
            Id::TTF => AV::TTF,

            Id::SCTE_35 => AV::SCTE_35,
            Id::BINTEXT => AV::BINTEXT,
            Id::XBIN => AV::XBIN,
            Id::IDF => AV::IDF,
            Id::OTF => AV::OTF,
            Id::SMPTE_KLV => AV::SMPTE_KLV,
            Id::DVD_NAV => AV::DVD_NAV,
            Id::TIMED_ID3 => AV::TIMED_ID3,
            Id::BIN_DATA => AV::BIN_DATA,

            Id::PROBE => AV::PROBE,

            Id::MPEG2TS => AV::MPEG2TS,
            Id::MPEG4SYSTEMS => AV::MPEG4SYSTEMS,
            Id::FFMETADATA => AV::FFMETADATA,
            Id::WRAPPED_AVFRAME => AV::WRAPPED_AVFRAME,

            Id::PSD => AV::PSD,
            Id::PIXLET => AV::PIXLET,
            Id::SPEEDHQ => AV::SPEEDHQ,
            Id::FMVC => AV::FMVC,
            Id::CLEARVIDEO => AV::CLEARVIDEO,
            Id::SCPR => AV::SCPR,
            Id::XPM => AV::XPM,
            Id::AV1 => AV::AV1,
            Id::PCM_F16LE => AV::PCM_F16LE,
            Id::PCM_F24LE => AV::PCM_F24LE,
            Id::ATRAC3AL => AV::ATRAC3AL,
            Id::ATRAC3PAL => AV::ATRAC3PAL,

            Id::BITPACKED => AV::BITPACKED,
            Id::MSCC => AV::MSCC,
            Id::SRGC => AV::SRGC,
            Id::SVG => AV::SVG,
            Id::GDV => AV::GDV,
            Id::FITS => AV::FITS,
            Id::GREMLIN_DPCM => AV::GREMLIN_DPCM,
            Id::DOLBY_E => AV::DOLBY_E,

            Id::APTX => AV::APTX,
            Id::APTX_HD => AV::APTX_HD,
            Id::SBC => AV::SBC,

            Id::AVS2 => AV::AVS2,
            Id::IMM4 => AV::IMM4,
            Id::PROSUMER => AV::PROSUMER,
            Id::MWSC => AV::MWSC,
            Id::WCMV => AV::WCMV,
            Id::RASC => AV::RASC,
            Id::PCM_VIDC => AV::PCM_VIDC,
            Id::ATRAC9 => AV::ATRAC9,
            Id::TTML => AV::TTML,

            Id::HYMT => AV::HYMT,
            Id::ARBC => AV::ARBC,
            Id::AGM => AV::AGM,
            Id::LSCR => AV::LSCR,
            Id::VP4 => AV::VP4,
            Id::ADPCM_AGM => AV::ADPCM_AGM,
            Id::HCOM => AV::HCOM,
            Id::ARIB_CAPTION => AV::ARIB_CAPTION,

            #[cfg(feature = "ffmpeg_4_3")]
            Id::IMM5 => AV::IMM5,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MVDV => AV::MVDV,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MVHA => AV::MVHA,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::CDTOONS => AV::CDTOONS,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MV30 => AV::MV30,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::NOTCHLC => AV::NOTCHLC,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::PFM => AV::PFM,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_ARGO => AV::ADPCM_ARGO,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_SSI => AV::ADPCM_IMA_SSI,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_ZORK => AV::ADPCM_ZORK,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_APM => AV::ADPCM_IMA_APM,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_ALP => AV::ADPCM_IMA_ALP,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_MTF => AV::ADPCM_IMA_MTF,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_CUNNING => AV::ADPCM_IMA_CUNNING,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::DERF_DPCM => AV::DERF_DPCM,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ACELP_KELVIN => AV::ACELP_KELVIN,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MPEGH_3D_AUDIO => AV::MPEGH_3D_AUDIO,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::SIREN => AV::SIREN,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::HCA => AV::HCA,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::EPG => AV::EPG,

            #[cfg(feature = "ffmpeg_4_4")]
            Id::PGX => AV::PGX,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::AVS3 => AV::AVS3,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::MSP2 => AV::MSP2,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::VVC => AV::VVC,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::MOBICLIP => AV::MOBICLIP,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::PHOTOCD => AV::PHOTOCD,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::IPU => AV::IPU,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::ARGO => AV::ARGO,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::CRI => AV::CRI,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::SIMBIOSIS_IMX => AV::SIMBIOSIS_IMX,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::SGA_VIDEO => AV::SGA_VIDEO,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::PCM_SGA => AV::PCM_SGA,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::ADPCM_IMA_MOFLEX => AV::ADPCM_IMA_MOFLEX,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::FASTAUDIO => AV::FASTAUDIO,

            #[cfg(feature = "ffmpeg_5_0")]
            Id::GEM => AV::GEM,
            #[cfg(feature = "ffmpeg_5_0")]
            Id::ADPCM_IMA_ACORN => AV::ADPCM_IMA_ACORN,
            #[cfg(feature = "ffmpeg_5_0")]
            Id::MSNSIREN => AV::MSNSIREN,

            #[cfg(feature = "ffmpeg_5_1")]
            Id::VBN => AV::VBN,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::JPEGXL => AV::JPEGXL,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::QOI => AV::QOI,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::PHM => AV::PHM,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::DFPWM => AV::DFPWM,

            #[cfg(feature = "ffmpeg_6_0")]
            Id::RADIANCE_HDR => AV::RADIANCE_HDR,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::WBMP => AV::WBMP,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::MEDIA100 => AV::MEDIA100,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::VQC => AV::VQC,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::ADPCM_XMD => AV::ADPCM_XMD,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::WADY_DPCM => AV::WADY_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::CBD2_DPCM => AV::CBD2_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::BONK => AV::BONK,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::MISC4 => AV::MISC4,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::APAC => AV::APAC,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::FTR => AV::FTR,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::WAVARC => AV::WAVARC,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::RKA => AV::RKA,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::VNULL => AV::VNULL,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::ANULL => AV::ANULL,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::PDV => AV::PDV,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::EVC => AV::EVC,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::RTV1 => AV::RTV1,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::VMIX => AV::VMIX,
            #[cfg(feature = "ffmpeg_7_0")]
            Id::LEAD => AV::LEAD,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::AC4 => AV::AC4,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::OSQ => AV::OSQ,
            #[cfg(feature = "ffmpeg_7_0")]
            Id::QOA => AV::QOA,
            #[cfg(feature = "ffmpeg_7_1")]
            Id::LC3 => AV::LC3,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::SMPTE_2038 => AV::SMPTE_2038,
            #[cfg(feature = "ffmpeg_7_1")]
            Id::LCEVC => AV::LCEVC,

            #[cfg(feature = "ffmpeg_8_0")]
            Id::DNXUC => AV::DNXUC,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::RV60 => AV::RV60,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::JPEGXL_ANIM => AV::JPEGXL_ANIM,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::APV => AV::APV,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::PRORES_RAW => AV::PRORES_RAW,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::ADPCM_IMA_XBOX => AV::ADPCM_IMA_XBOX,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::ADPCM_SANYO => AV::ADPCM_SANYO,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::G728 => AV::G728,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::IVTV_VBI => AV::IVTV_VBI,
            #[cfg(feature = "ffmpeg_8_0")]
            Id::SMPTE_436M_ANC => AV::SMPTE_436M_ANC,
        }
    }
}
